"""Split an autogenerated revision so each app owns its own file."""

from __future__ import annotations

import sys
from collections.abc import Sequence
from typing import Any

from fastframe.core.apps import AppsRegistry
from fastframe.migrations.paths import FRAMEWORK_MIGRATION_APP
from fastframe.models.base import Model, ModelMeta


def table_owners(registry: AppsRegistry) -> dict[str, str]:
    """Map table name to the app that owns it.

    Framework apps (dotted names) share the ``config`` owner. Many-to-many
    join tables belong to the app that declared the field.
    """
    from fastframe.models.fields import ManyToManyField

    owners: dict[str, str] = {}
    for app_config in registry.app_configs:
        models_module = sys.modules.get(f"{app_config.name}.models")
        if models_module is None:
            continue
        owner = FRAMEWORK_MIGRATION_APP if "." in app_config.name else app_config.name
        for attr_name in dir(models_module):
            attr = getattr(models_module, attr_name)
            if not _is_model(attr):
                continue
            owners[attr.__tablename__] = owner
            fields = getattr(attr, "_fields_for_fk_setup", {}) or {}
            for field_name, field in fields.items():
                if isinstance(field, ManyToManyField):
                    table_name = field.db_table or f"{attr.__tablename__}_{field_name}"
                    owners[table_name] = owner
    return owners


def _is_model(attr: Any) -> bool:
    return (
        isinstance(attr, ModelMeta)
        and issubclass(attr, Model)
        and attr is not Model
        and getattr(attr, "__tablename__", None)
    )


def operation_table(op: Any) -> str | None:
    """Table an autogenerate operation applies to, when it has one."""
    for attr in ("table_name", "source_table"):
        value = getattr(op, attr, None)
        if isinstance(value, str) and value:
            return value
    table = getattr(op, "table", None)
    name = getattr(table, "name", None)
    if isinstance(name, str) and name:
        return name
    return None


def group_operations(
    upgrade_ops: Sequence[Any],
    downgrade_ops: Sequence[Any],
    owners: dict[str, str],
    app_order: Sequence[str],
    *,
    only: set[str] | None = None,
) -> tuple[list[tuple[str, list[Any], list[Any]]], list[str]]:
    """Bucket operations by owning app, preserving op order inside a bucket.

    Returns ``(groups, skipped_apps)``. ``skipped_apps`` lists owners that
    had changes but were excluded by ``only``.
    """
    order = list(app_order)
    upgrade_by_app: dict[str, list[Any]] = {name: [] for name in order}
    downgrade_by_app: dict[str, list[Any]] = {name: [] for name in order}

    def bucket(op: Any, target: dict[str, list[Any]]) -> str | None:
        table = operation_table(op)
        owner = owners.get(table) if table else None
        if owner is None or owner not in target:
            # Keep unattributed operations with framework migrations rather
            # than silently dropping them or stuffing them into the first app.
            owner = FRAMEWORK_MIGRATION_APP if FRAMEWORK_MIGRATION_APP in target else order[0]
        target[owner].append(op)
        return owner

    seen: set[str] = set()
    for op in upgrade_ops:
        owner = bucket(op, upgrade_by_app)
        if owner:
            seen.add(owner)
    for op in downgrade_ops:
        bucket(op, downgrade_by_app)

    skipped = [name for name in order if name in seen and only is not None and name not in only]
    selected = [name for name in order if upgrade_by_app[name] and (only is None or name in only)]
    groups = [
        (name, upgrade_by_app[name], downgrade_by_app[name])
        for name in selected
    ]
    return groups, skipped
