from __future__ import annotations

import os

from alembic import command
from alembic.config import Config

from fastframe.core.bootstrap import bootstrap, get_apps_registry
from fastframe.core.settings import load_settings
from fastframe.db.engine import get_engine
from fastframe.migrations.paths import (
    default_version_path,
    get_script_location,
    get_version_locations,
)


def build_alembic_config(settings_module: str | None = None) -> Config:
    bootstrap(settings_module)
    settings = load_settings(settings_module)
    registry = get_apps_registry()
    script_location = get_script_location(settings_module)
    cfg = Config()
    cfg.set_main_option("script_location", str(script_location))
    cfg.set_main_option("sqlalchemy.url", settings.DATABASE_URL)
    version_locations = get_version_locations(registry, settings_module)
    cfg.set_main_option("path_separator", "os")
    cfg.set_main_option(
        "version_locations",
        os.pathsep.join(str(path) for path in version_locations),
    )
    return cfg


def makemigrations(message: str = "auto", settings_module: str | None = None) -> None:
    """Generate a new migration if schema changes are detected."""
    cfg = build_alembic_config(settings_module)
    registry = get_apps_registry()
    version_path = str(default_version_path(registry, settings_module))
    
    # Track whether autogenerate detected changes
    detected_changes = False

    def process_revision_directives(context, revision, directives):
        nonlocal detected_changes
        if directives[0].upgrade_ops.is_empty():
            # No schema changes detected
            directives[:] = []
        else:
            detected_changes = True

    command.revision(
        cfg,
        message=message,
        autogenerate=True,
        version_path=version_path,
        process_revision_directives=process_revision_directives,
    )
    
    if not detected_changes:
        print("No changes detected.")


def migrate(revision: str = "head", settings_module: str | None = None) -> None:
    cfg = build_alembic_config(settings_module)
    command.upgrade(cfg, revision)


def showmigrations(settings_module: str | None = None) -> None:
    """Print every migration with an `[X]`/`[ ]` applied marker.

    v0.1/v0.2 write all autogenerated revisions into a single chain (the
    first installed app with models, or `config/migrations` if none have
    models yet) rather than one independent chain per app — see
    docs/app-contract.md. So this prints one combined, chronological list
    rather than grouping by app.
    """
    from alembic.runtime.migration import MigrationContext
    from alembic.script import ScriptDirectory

    cfg = build_alembic_config(settings_module)
    script = ScriptDirectory.from_config(cfg)

    revisions = list(script.walk_revisions())
    if not revisions:
        print("No migrations found. Run `manage.py makemigrations`.")
        return

    try:
        engine = get_engine(settings_module)
        with engine.connect() as conn:
            context = MigrationContext.configure(conn)
            current_heads = set(context.get_current_heads())
    except Exception as exc:  # noqa: BLE001 - degrade to "unknown applied state"
        print(f"Could not determine applied migrations: {exc}\n")
        current_heads = set()

    applied: set[str] = set()
    for head in current_heads:
        for rev in script.walk_revisions(base="base", head=head):
            applied.add(rev.revision)

    # walk_revisions() with no base/head walks newest -> oldest across all
    # heads; reverse for a chronological, top-to-bottom read.
    for rev in reversed(revisions):
        marker = "X" if rev.revision in applied else " "
        doc = rev.doc or ""
        print(f" [{marker}] {rev.revision} {doc}".rstrip())
