"""Each app's autogenerated migration stays in that app's directory."""

from __future__ import annotations

import shutil
from pathlib import Path
from types import SimpleNamespace

from fastframe.migrations.ownership import group_operations
from fastframe.migrations.paths import FRAMEWORK_MIGRATION_APP


def test_group_operations_keeps_each_apps_tables_together() -> None:
    bakery_create = SimpleNamespace(table_name="bakery_pastries")
    cinema_create = SimpleNamespace(table_name="cinema_movies")
    bakery_drop = SimpleNamespace(table_name="bakery_pastries")
    cinema_drop = SimpleNamespace(table_name="cinema_movies")
    owners = {
        "bakery_pastries": "bakery",
        "cinema_movies": "cinema",
    }

    groups, skipped = group_operations(
        [bakery_create, cinema_create],
        [cinema_drop, bakery_drop],
        owners,
        ["bakery", "cinema"],
    )

    assert skipped == []
    assert [name for name, _, _ in groups] == ["bakery", "cinema"]
    assert groups[0][1] == [bakery_create]
    assert groups[0][2] == [bakery_drop]
    assert groups[1][1] == [cinema_create]
    assert groups[1][2] == [cinema_drop]


def test_group_operations_can_limit_to_requested_apps() -> None:
    bakery = SimpleNamespace(table_name="bakery_pastries")
    cinema = SimpleNamespace(table_name="cinema_movies")
    groups, skipped = group_operations(
        [bakery, cinema],
        [],
        {"bakery_pastries": "bakery", "cinema_movies": "cinema"},
        ["bakery", "cinema"],
        only={"bakery"},
    )
    assert [name for name, _, _ in groups] == ["bakery"]
    assert skipped == ["cinema"]


def test_framework_tables_are_not_assigned_to_the_first_app() -> None:
    auth = SimpleNamespace(table_name="auth_users")
    todo = SimpleNamespace(table_name="todos")
    groups, skipped = group_operations(
        [auth, todo],
        [],
        {"auth_users": FRAMEWORK_MIGRATION_APP, "todos": "todo"},
        [FRAMEWORK_MIGRATION_APP, "todo"],
    )
    assert skipped == []
    assert [name for name, _, _ in groups] == [FRAMEWORK_MIGRATION_APP, "todo"]
    assert groups[0][1] == [auth]
    assert groups[1][1] == [todo]


def test_makemigrations_writes_new_model_into_its_own_app(
    miniproject_env, miniproject_path: Path, monkeypatch
) -> None:
    notes = miniproject_path / "notes"
    versions = notes / "migrations" / "versions"
    users_before = {
        path.name
        for path in (miniproject_path / "users" / "migrations" / "versions").glob("*.py")
    }
    try:
        notes.mkdir()
        (notes / "__init__.py").write_text("")
        (notes / "apps.py").write_text(
            "from fastframe.core.apps import AppConfig\n\n"
            "class NotesConfig(AppConfig):\n"
            "    name = 'notes'\n"
            "    label = 'notes'\n"
        )
        (notes / "models.py").write_text(
            "from fastframe.models import Model, fields\n\n"
            "class Note(Model):\n"
            "    title = fields.CharField(max_length=80)\n\n"
            "    class Meta:\n"
            "        db_table = 'notes'\n"
            "        app_label = 'notes'\n"
        )
        import config.settings as project_settings

        from fastframe.core.bootstrap import bootstrap, reset_bootstrap

        monkeypatch.setattr(
            project_settings,
            "INSTALLED_APPS",
            [*project_settings.INSTALLED_APPS, "notes"],
        )
        reset_bootstrap()
        bootstrap(None)

        from fastframe.migrations.runner import makemigrations, migrate

        # Re-bootstrap opens a fresh in-memory database. Apply the existing
        # revisions first so autogenerate is comparing against a current head.
        migrate()
        makemigrations(message="add notes")

        written = list(versions.glob("*.py"))
        assert len(written) == 1
        text = written[0].read_text()
        assert "create_table('notes'" in text
        assert "create_table('posts'" not in text
        assert "create_table('users'" not in text
        users_after = {
            path.name
            for path in (miniproject_path / "users" / "migrations" / "versions").glob("*.py")
        }
        assert users_after == users_before
    finally:
        shutil.rmtree(notes, ignore_errors=True)
        from fastframe.models.base import Model

        table = Model.metadata.tables.get("notes")
        if table is not None:
            Model.metadata.remove(table)
        import sys

        for name in ("notes", "notes.apps", "notes.models"):
            sys.modules.pop(name, None)
